export const mapCopy = {
  title: "خريطة تحركاتك.",
  subtitle: "كل شخص في مكانه على الخريطة دي، والمسافة دي حقك",
  addPersonLabel: "+ أضف شخص",
  addPersonTitle: "ابدأ بالشخص اللي بتحس إنه يثقل عليك الأكتر",
  feelingCta: "حلل إحساسك",
  feelingCtaDisabledHint: "أضف شخص الأول عشان تحلل إحساسك",
  ringsHint: "لون الدائرة = مستوى التهديد. حُسّك هو المقياس.",
  legendGreen: "قرب صحي",
  legendYellow: "قرب مشروط",
  legendRed: "خطر / استنزاف",
  legendGrey: "منطقة العزل (صيام شعوري)",
  threatLevelHint: "الحلقة حول كل جبهة = مستوى التهديد",
  placementTitle: "ضعه في الخريطة",
  placementHint: "اسحب الشخص وضعه في الدائرة اللي تعكس شعورك: قرب صحي، مشروط، أو خطر.",
  confirmPlacement: "تأكيد المكان",
  firstPlacementTooltip: "تقدر تضغط على الشخص وتعدّل أو تفهم أكتر.",
  /** حالة الخريطة الفاضية — placeholder يظهر لما مفيش أشخاص */
  emptyMapTitle: "ابدأ بأول شخص",
  emptyMapHint: "اختار الشخص اللي بتحس إنه يثقل عليك أكتر حاجة، ضعه على الخريطة، وأخبرنا شعورك.",
  emptyMapReassurance: "كل إضافة هتساعد الخريطة تصير واضحة أكتر.",
  /** شجرة العيلة — عرض هرمي */
  familyTreeTitle: "شجرة العيلة",
  familyTreeSubtitle: "من هنا بدأت الحكاية",
  familyTreeHint: "لون الدائرة = مكانهم في الخريطة (قرب صحي / مشروط / استنزاف). اضغط على الشخص للتفاصيل.",
  familyTreeEmpty: "مافيش أشخاص. اضف أشخاص من الخريطة أولاً.",
  galaxyTitle: "جميع الجبهات",
  galaxyHint: "كل الأشخاص من كل السياقات في مكان واحد. استخدم الفلاتر عشان تركز.",
  forestTitle: "المسار الموحد",
  forestHint: "عناقيد الأشخاص: العيلة، الشغل، الأصدقاء، الحب.",
  viewAllCta: "عرض الكل",
  viewSingleCta: "سياق واحد",
  contextFamily: "العيلة 👨‍👩‍👧‍👦",
  contextWork: "الشغل 💼",
  contextLove: "الحب 💕",
  contextGeneral: "أخرى 📍",
  insightInheritedPattern: (rootLabel: string) =>
    `ملاحظة: يبدو إن فيه نمط استنزاف متوارث في ناحية ${rootLabel}. هل تريد تركيزاً خاصاً على الصدمات المتوارثة في بروتوكول الدفاع؟`,
  focusTraumaRecoveryCta: "نعم، ركّز على الصدمات المتوارثة",
  focusTraumaBadge: "تركيز: الصدمات المتوارثة",
  /** مسار الاستقلال العاطفي */
  detachmentTitle: "الاستقلال العاطفي",
  detachmentRealityAnchor: "أساسك الثابت",
  detachmentRealityAnchorHint: "اكتب 3 أسباب قوية لماذا قررت المسافة. عندما تشعر بالضعف، عُد إليها.",
  detachmentRealityAnchorPlaceholder: "مثال: لما قال/قالت…",
  detachmentWeakButton: "وحشني / حاسس بضعف",
  detachmentRumination: "سجل الاجترار",
  detachmentRuminationButton: "أنا بفكر فيه دلوقتي",
  detachmentRuminationPrompt: "الفكرة دي نوعها إيه؟",
  detachmentRuminationOptions: { guilt: "ذنب مزيف", nostalgia: "حنين للماضي", fear: "خوف" } as const,
  detachmentRuminationResponse: "دي مجرد فكرة، مش واقع. خلّيها تعدي.",
  /** إشارة قف — أول ما الفكرة تيجي يضغط ويهتز ويقول الجملة */
  detachmentStopSignButton: "مش هنا.. مش دلوقتي.. ومش أنا اللي هحلها",
  detachmentStopSignHint: "اضغط أول ما صورته تيجي في بالك — اهتزاز + جملة وقف.",
  /** محكمة الضمير — المستخدم يكتب جملة ذنب وياخد رد إعادة صياغة */
  detachmentGuiltCourtTitle: "محكمة الضمير",
  detachmentGuiltCourtHint: "اكتب جملة ذنب (مثلاً: حاسس بذنب إني مكلمتهاش) واعرض ردّ القاضي.",
  detachmentGuiltCourtPlaceholder: "مثال: حاسس بذنب إني مكلمتهاش",
  detachmentGuiltCourtButton: "كن القاضي — اعرض الرد",
  detachmentGuiltCourtStaticResponse: "هل فيه قانون بيقول لازم تكلمها كل يوم؟ ولا ده قانون هي اللي حطته؟ كن أنت القاضي مش المتهم.",
  tabDiagnosis: "التشخيص",
  tabSymptoms: "الأعراض",
  tabSolution: "الحل",
  tabPlan: "بروتوكول الدفاع",
  firstStepCta: "ابدأ مهمات الميدان",
  /** تبويب التشخيص — بسيط افتراضيًا، التفاصيل قابلة للطي */
  diagnosisReadMore: "اقرأ فهم الوضع",
  diagnosisReadInsight: "رؤية إضافية",
  diagnosisCollapse: "أخفِ",
  /** شرط الخطة — يظهر في تبويب الخطة وأول خطوة عشان مفيش حد يسأل "ليه الخطة مش بتطلع؟" */
  planRuleTitle: "ليه بروتوكول الدفاع مش ظاهر؟",
  planRuleBody: "المهمات الأسبوعية بتظهر لما تكتب موقفين على الأقل في «الخطوة الأولى». المواقف دي بتساعدنا نحلل الأنماط ونولّد بروتوكول مخصص ليك.",
  planRuleCounter: (count: number) => `مواقفك الحالية: ${count}/2`,
  planRuleCta: "روح اكتب المواقف ←",
  planRuleShort: "بروتوكول الدفاع يظهر بعد موقفين فقط.",
  planPreviewTitle: "معاينة بروتوكول الدفاع",
  planPreviewCta: "اكتب موقفين عشان نولّد لك بروتوكول مخصص كامل.",
  /** أونبوردينج الخريطة — يظهر مرة واحدة للمستخدم الجديد */
  onboardingStep1: "أنت في المركز. الخريطة دي مملكتك — تحددي من يقترب وكام.",
  onboardingStep2: "لون الدائرة = شعورك: أخضر = صحي، أصفر = مشروط (فيه حدود)، أحمر = خطر (استنزاف).",
  onboardingCta: "فهمت",

  // Dynamic titles based on goalId
  titles: {
    family: "خريطة العيلة",
    work: "خريطة الشغل",
    love: "خريطة الحب",
    money: "خريطة الفلوس",
    unknown: "خريطتك",
    general: "خريطتك"
  }
};

