export const mapCopy = {
  title: "خريطة مداراتك",
  subtitle: "كل شخص في مداره، والمسافة بينكم أنت اللي بتحددها",
  addPersonLabel: "+ أضف شخص",
  addPersonTitle: "ابدأ بالشخص اللي واخد أكبر مساحة من طاقتك",
  feelingCta: "استكشف إحساسك",
  feelingCtaDisabledHint: "أضف شخص الأول عشان تستكشف إحساسك",
  ringsHint: "لون المدار = قرب الشخص من طاقتك. إحساسك هو البوصلة.",
  legendGreen: "مدار قريب",
  legendYellow: "مدار متذبذب",
  legendRed: "مدار بعيد",
  legendGrey: "مساحة الراحة",
  threatLevelHint: "الحلقة حول كل شخص = مستوى تأثيره على طاقتك",
  placementTitle: "حطه في مداره",
  placementHint: "اسحب الشخص وحطه في المدار اللي يعبّر عن إحساسك: قريب، متذبذب، أو بعيد.",
  confirmPlacement: "ثبّت المكان",
  firstPlacementTooltip: "تقدر تضغط على الشخص وتفهم أكتر أو تعدّل مكانه.",
  /** حالة الخريطة الفاضية */
  emptyMapTitle: "ابدأ بأول شخص",
  emptyMapHint: "اختار الشخص اللي واخد أكبر مساحة من طاقتك، حطه في المدار، وقولنا إحساسك.",
  emptyMapReassurance: "كل إضافة بتخلي الصورة أوضح.",
  /** شجرة العيلة */
  familyTreeTitle: "شجرة العيلة",
  familyTreeSubtitle: "من هنا بدأت الحكاية",
  familyTreeHint: "لون المدار = مكانهم في الخريطة (قريب / متذبذب / بعيد). اضغط على الشخص للتفاصيل.",
  familyTreeEmpty: "مفيش أشخاص لسه. أضف أشخاص من الخريطة الأول.",
  galaxyTitle: "كل المدارات",
  galaxyHint: "كل الأشخاص من كل السياقات في مكان واحد. استخدم الفلاتر عشان تركز.",
  forestTitle: "المسار الموحد",
  forestHint: "مجموعات الأشخاص: العيلة، الشغل، الأصدقاء، الحب.",
  viewAllCta: "عرض الكل",
  viewSingleCta: "سياق واحد",
  contextFamily: "العيلة 👨‍👩‍👧‍👦",
  contextWork: "الشغل 💼",
  contextLove: "الحب 💕",
  contextGeneral: "أخرى 📍",
  insightInheritedPattern: (rootLabel: string) =>
    `ملاحظة: يبدو إن فيه نمط متوارث في ناحية ${rootLabel} بياخد مساحة من طاقتك. تحب نركز عليه في مسار الحماية؟`,
  focusTraumaRecoveryCta: "أيوه، نركز على الأنماط المتوارثة",
  focusTraumaBadge: "تركيز: الأنماط المتوارثة",
  /** مساحة التعافي */
  detachmentTitle: "مساحة التعافي",
  detachmentRealityAnchor: "أساسك الثابت",
  detachmentRealityAnchorHint: "اكتب ٣ أسباب قوية لاختيارك للمسافة. لما تحس بتذبذب، ارجع لهم.",
  detachmentRealityAnchorPlaceholder: "مثال: لما حصل...",
  detachmentWeakButton: "وحشني / حاسس بتذبذب",
  detachmentRumination: "سجل الأفكار",
  detachmentRuminationButton: "أنا بفكر فيه دلوقتي",
  detachmentRuminationPrompt: "الفكرة دي شكلها إيه؟",
  detachmentRuminationOptions: { guilt: "ذنب مش حقيقي", nostalgia: "حنين للماضي", fear: "خوف" } as const,
  detachmentRuminationResponse: "دي فكرة عابرة، مش واقعك. سيبها تعدي.",
  /** إشارة وقف */
  detachmentStopSignButton: "مش هنا.. مش دلوقتي.. وأنا مش مسؤول عن ده",
  detachmentStopSignHint: "اضغط أول ما صورته تيجي في بالك — اهتزاز + جملة وقف.",
  /** ميزان الضمير */
  detachmentGuiltCourtTitle: "ميزان الضمير",
  detachmentGuiltCourtHint: "اكتب جملة الذنب اللي جواك واسمع الرد الهادي.",
  detachmentGuiltCourtPlaceholder: "مثال: حاسس بذنب إني مكلمتهاش",
  detachmentGuiltCourtButton: "اسمع الرد الهادي",
  detachmentGuiltCourtStaticResponse: "هل فيه قانون بيقول لازم تكلمها كل يوم؟ ولا ده قانون هي اللي حطته؟ أنت مش المتهم هنا.",
  tabDiagnosis: "فهم الوضع",
  tabSymptoms: "الإشارات",
  tabSolution: "الخطوة الجاية",
  tabPlan: "مسار الحماية",
  firstStepCta: "ابدأ خطوات الرحلة",
  /** تبويب التشخيص */
  diagnosisReadMore: "اقرأ فهم الوضع",
  diagnosisReadInsight: "رؤية إضافية",
  diagnosisCollapse: "أخفِ",
  /** شرط الخطة */
  planRuleTitle: "ليه مسار الحماية مش ظاهر؟",
  planRuleBody: "خطوات الرحلة بتظهر لما تكتب موقفين على الأقل في «الخطوة الأولى». المواقف دي بتساعدنا نفهم الأنماط ونرسم لك مسار مخصص.",
  planRuleCounter: (count: number) => `مواقفك الحالية: ${count}/2`,
  planRuleCta: "يلا نكتب المواقف ←",
  planRuleShort: "مسار الحماية يظهر بعد موقفين.",
  planPreviewTitle: "معاينة مسار الحماية",
  planPreviewCta: "اكتب موقفين عشان نرسم لك مسار مخصص كامل.",
  /** أونبوردينج الخريطة */
  onboardingStep1: "أنت في المركز. المساحة دي بتاعتك — أنت اللي بتحدد المسافات.",
  onboardingStep2: "لون المدار = إحساسك: أخضر = قريب، أصفر = متذبذب، أحمر = بعيد.",
  onboardingCta: "فهمت، يلا بينا",

  // Dynamic titles based on goalId
  titles: {
    family: "خريطة العيلة",
    work: "خريطة الشغل",
    love: "خريطة الحب",
    money: "خريطة الفلوس",
    unknown: "خريطتك",
    general: "خريطتك"
  }
};
