export const mapCopy = {
  title: "أنا المركز.",
  subtitle: "من هنا بدأت الحكاية",
  addPersonLabel: "أضف جبهة",
  addPersonTitle: "ابدأ بأكتر جبهة (شخص) حاسس إنها قريبة وضاغطة عليك",
  feelingCta: "حلل إحساسك",
  feelingCtaDisabledHint: "أضف شخص الأول عشان تحلل إحساسك",
  ringsHint: "حُسّك مهم. مش محتاج تبرر.",
  legendGreen: "قرب صحي",
  legendYellow: "قرب مشروط",
  legendRed: "خطر / استنزاف",
  legendGrey: "منطقة العزل (صيام شعوري)",
  threatLevelHint: "الحلقة حول كل جبهة = مستوى التهديد",
  placementTitle: "ضعه في الخريطة",
  placementHint: "اسحب الدائرة وارمِها في المنطقة اللي تناسب",
  confirmPlacement: "تأكيد المكان",
  firstPlacementTooltip: "تقدر تضغط على الشخص وتعدّل أو تفهم أكتر.",
  /** حالة الخريطة الفاضية — placeholder يظهر لما مفيش أشخاص */
  emptyMapTitle: "الميدان فاضي دلوقتي",
  emptyMapHint: "اضغط «أضف جبهة» فوق عشان تضع أول علاقة وتبدأ.",
  /** شجرة العيلة — عرض هرمي */
  familyTreeTitle: "شجرة العيلة",
  familyTreeSubtitle: "من هنا بدأت الحكاية",
  familyTreeHint: "لون الدائرة = مكانهم في الخريطة (قرب صحي / مشروط / استنزاف). اضغط على الشخص للتفاصيل.",
  familyTreeEmpty: "مافيش أشخاص. اضف أشخاص من الخريطة أولاً.",
  galaxyTitle: "الخريطة العامة",
  galaxyHint: "كل علاقاتك من كل السياقات. استخدم الفلتر لإظهار/إخفاء عيلة، شغل، حب.",
  forestTitle: "الغابة",
  forestHint: "عناقيد: عيلة، شغل، أصدقاء.",
  viewAllCta: "عرض الكل",
  viewSingleCta: "سياق واحد",
  contextFamily: "عيلة",
  contextWork: "شغل",
  contextLove: "حب",
  contextGeneral: "أخرى",
  insightInheritedPattern: (rootLabel: string) =>
    `ملاحظة: يبدو إن فيه نمط استنزاف متوارث في ناحية ${rootLabel}. تحب نركز على توارث الصدمات في بروتوكول الدفاع؟`,
  focusTraumaRecoveryCta: "نعم، ركّز على توارث الصدمات",
  focusTraumaBadge: "تركيز: توارث الصدمات",
  /** مسار فك الارتباط الشعوري */
  detachmentTitle: "فك الارتباط الشعوري",
  detachmentRealityAnchor: "مرساة الواقع",
  detachmentRealityAnchorHint: "اكتب 3 مواقف أو أسباب خلوك تبعد أصلاً. لما تحس بحنين أو ضعف، ارجع ليهم.",
  detachmentRealityAnchorPlaceholder: "مثال: لما قال/قالت…",
  detachmentWeakButton: "وحشني / حاسس بضعف",
  detachmentRumination: "سجل الاجترار",
  detachmentRuminationButton: "أنا بفكر فيه دلوقتي",
  detachmentRuminationPrompt: "الفكرة دي نوعها إيه؟",
  detachmentRuminationOptions: { guilt: "ذنب مزيف", nostalgia: "حنين للماضي", fear: "خوف" } as const,
  detachmentRuminationResponse: "دي مجرد فكرة، مش واقع. خلّيها تعدي.",
  /** إشارة قف — أول ما الفكرة تيجي يضغط ويهتز ويقول الجملة */
  detachmentStopSignButton: "مش هنا.. مش دلوقتي",
  detachmentStopSignHint: "اضغط أول ما صورته تيجي في بالك — اهتزاز + جملة وقف.",
  /** محكمة الضمير — المستخدم يكتب جملة ذنب وياخد رد إعادة صياغة */
  detachmentGuiltCourtTitle: "محكمة الضمير",
  detachmentGuiltCourtHint: "اكتب جملة ذنب (مثلاً: حاسس بذنب إني مكلمتهاش) واعرض ردّ القاضي.",
  detachmentGuiltCourtPlaceholder: "مثال: حاسس بذنب إني مكلمتهاش",
  detachmentGuiltCourtButton: "كن القاضي — اعرض الرد",
  detachmentGuiltCourtStaticResponse: "هل فيه قانون بيقول لازم تكلمها كل يوم؟ ولا ده قانون هي اللي حطته؟ كن أنت القاضي مش المتهم.",
  tabDiagnosis: "التشخيص",
  tabSymptoms: "الأعراض",
  tabSolution: "الحل",
  tabPlan: "بروتوكول الدفاع",
  firstStepCta: "ابدأ مهمات الميدان",
  /** تبويب التشخيص — بسيط افتراضيًا، التفاصيل قابلة للطي */
  diagnosisReadMore: "اقرأ فهم الوضع",
  diagnosisReadInsight: "رؤية إضافية",
  diagnosisCollapse: "أخفِ",
  /** شرط الخطة — يظهر في تبويب الخطة وأول خطوة عشان مفيش حد يسأل "ليه الخطة مش بتطلع؟" */
  planRuleTitle: "ليه بروتوكول الدفاع مش ظاهر؟",
  planRuleBody: "المهمات الأسبوعية بتظهر لما تكتب موقفين على الأقل في «الخطوة الأولى». المواقف دي بتساعدنا نحلل الأنماط ونولّد بروتوكول مخصص ليك.",
  planRuleCounter: (count: number) => `مواقفك الحالية: ${count}/2`,
  planRuleCta: "روح اكتب المواقف ←",
  planRuleShort: "بروتوكول الدفاع يظهر بعد موقفين فقط.",
  planPreviewTitle: "معاينة بروتوكول الدفاع",
  planPreviewCta: "اكتب موقفين عشان نولّد لك بروتوكول مخصص كامل.",
  /** أونبوردينج الخريطة — يظهر مرة واحدة للمستخدم الجديد */
  onboardingStep1: "أنت في المركز. الخريطة دي مملكتك، ومحدش يدخلها غير بإذنك.",
  onboardingStep2: "الدوائر الثلاث: أخضر = قرب صحي، أصفر = قرب مشروط، أحمر = خطر أو استنزاف. ضع كل جبهة في الدائرة اللي تناسب.",
  onboardingCta: "فهمت",

  // Dynamic titles based on goalId
  titles: {
    family: "خريطة العيلة",
    work: "خريطة الشغل",
    love: "خريطة الحب",
    money: "خريطة الفلوس",
    unknown: "خريطتك",
    general: "خريطتك"
  }
};

