# Generated by Django 5.2.13 on 2026-04-18 21:15

import django.db.models.deletion
import nexus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', nexus.models.SovereignEncryptedField(verbose_name='البصيرة المشفرة')),
                ('category', models.CharField(default='general', max_length=100, verbose_name='التصنيف')),
                ('energy_level', models.IntegerField(default=5, verbose_name='مستوى الطاقة')),
                ('exercise_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='كود التمرين')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بصيرة المستخدم',
                'verbose_name_plural': 'بصائر المستخدمين',
                'ordering': ['-created_at'],
            },
        ),
    ]
